apiVersion: apps/v1
kind: Deployment
metadata:
  name: blogappod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blogappod
  template:
    metadata:
      labels:
        app: blogappod
    spec:
      containers:
      - name: blogappod
        image: caiosantiago/blogapp:latest
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: blogapp-service
spec:
  selector:
    app: blogappod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer